apiVersion: v1
kind: Service
metadata:
  name: go-postgres-app
  labels:
    app: go-postgres-app
spec:
  selector:
    app: go-postgres-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http

